// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: tweet/tweet.proto

package tweet

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Tweet service

func NewTweetEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Tweet service

type TweetService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Tweet_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Tweet_PingPongService, error)
}

type tweetService struct {
	c    client.Client
	name string
}

func NewTweetService(name string, c client.Client) TweetService {
	return &tweetService{
		c:    c,
		name: name,
	}
}

func (c *tweetService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Tweet.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tweetService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Tweet_StreamService, error) {
	req := c.c.NewRequest(c.name, "Tweet.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &tweetServiceStream{stream}, nil
}

type Tweet_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type tweetServiceStream struct {
	stream client.Stream
}

func (x *tweetServiceStream) Close() error {
	return x.stream.Close()
}

func (x *tweetServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *tweetServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *tweetServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *tweetServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *tweetService) PingPong(ctx context.Context, opts ...client.CallOption) (Tweet_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Tweet.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &tweetServicePingPong{stream}, nil
}

type Tweet_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type tweetServicePingPong struct {
	stream client.Stream
}

func (x *tweetServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *tweetServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *tweetServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *tweetServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *tweetServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *tweetServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Tweet service

type TweetHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Tweet_StreamStream) error
	PingPong(context.Context, Tweet_PingPongStream) error
}

func RegisterTweetHandler(s server.Server, hdlr TweetHandler, opts ...server.HandlerOption) error {
	type tweet interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Tweet struct {
		tweet
	}
	h := &tweetHandler{hdlr}
	return s.Handle(s.NewHandler(&Tweet{h}, opts...))
}

type tweetHandler struct {
	TweetHandler
}

func (h *tweetHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.TweetHandler.Call(ctx, in, out)
}

func (h *tweetHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.TweetHandler.Stream(ctx, m, &tweetStreamStream{stream})
}

type Tweet_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type tweetStreamStream struct {
	stream server.Stream
}

func (x *tweetStreamStream) Close() error {
	return x.stream.Close()
}

func (x *tweetStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *tweetStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *tweetStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *tweetStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *tweetHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.TweetHandler.PingPong(ctx, &tweetPingPongStream{stream})
}

type Tweet_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type tweetPingPongStream struct {
	stream server.Stream
}

func (x *tweetPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *tweetPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *tweetPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *tweetPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *tweetPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *tweetPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
