// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: article.proto

package article

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/isfk/aio/proto/user"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Service service

func NewServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Service service

type Service interface {
	Create(ctx context.Context, in *Article, opts ...client.CallOption) (*Article, error)
	Update(ctx context.Context, in *Article, opts ...client.CallOption) (*Article, error)
	Delete(ctx context.Context, in *Article, opts ...client.CallOption) (*Article, error)
	InfoByID(ctx context.Context, in *ID, opts ...client.CallOption) (*Article, error)
	ListByPage(ctx context.Context, in *ListReq, opts ...client.CallOption) (*ArticleList, error)
	CreateCategory(ctx context.Context, in *ArticleCategory, opts ...client.CallOption) (*ArticleCategory, error)
	UpdateCategory(ctx context.Context, in *ArticleCategory, opts ...client.CallOption) (*ArticleCategory, error)
	DeleteCategory(ctx context.Context, in *ArticleCategory, opts ...client.CallOption) (*ArticleCategory, error)
	CategoryInfoByID(ctx context.Context, in *ID, opts ...client.CallOption) (*ArticleCategory, error)
	CategoryListByPage(ctx context.Context, in *CategoryListReq, opts ...client.CallOption) (*ArticleCategoryList, error)
}

type service struct {
	c    client.Client
	name string
}

func NewService(name string, c client.Client) Service {
	return &service{
		c:    c,
		name: name,
	}
}

func (c *service) Create(ctx context.Context, in *Article, opts ...client.CallOption) (*Article, error) {
	req := c.c.NewRequest(c.name, "Service.Create", in)
	out := new(Article)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *service) Update(ctx context.Context, in *Article, opts ...client.CallOption) (*Article, error) {
	req := c.c.NewRequest(c.name, "Service.Update", in)
	out := new(Article)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *service) Delete(ctx context.Context, in *Article, opts ...client.CallOption) (*Article, error) {
	req := c.c.NewRequest(c.name, "Service.Delete", in)
	out := new(Article)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *service) InfoByID(ctx context.Context, in *ID, opts ...client.CallOption) (*Article, error) {
	req := c.c.NewRequest(c.name, "Service.InfoByID", in)
	out := new(Article)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *service) ListByPage(ctx context.Context, in *ListReq, opts ...client.CallOption) (*ArticleList, error) {
	req := c.c.NewRequest(c.name, "Service.ListByPage", in)
	out := new(ArticleList)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *service) CreateCategory(ctx context.Context, in *ArticleCategory, opts ...client.CallOption) (*ArticleCategory, error) {
	req := c.c.NewRequest(c.name, "Service.CreateCategory", in)
	out := new(ArticleCategory)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *service) UpdateCategory(ctx context.Context, in *ArticleCategory, opts ...client.CallOption) (*ArticleCategory, error) {
	req := c.c.NewRequest(c.name, "Service.UpdateCategory", in)
	out := new(ArticleCategory)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *service) DeleteCategory(ctx context.Context, in *ArticleCategory, opts ...client.CallOption) (*ArticleCategory, error) {
	req := c.c.NewRequest(c.name, "Service.DeleteCategory", in)
	out := new(ArticleCategory)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *service) CategoryInfoByID(ctx context.Context, in *ID, opts ...client.CallOption) (*ArticleCategory, error) {
	req := c.c.NewRequest(c.name, "Service.CategoryInfoByID", in)
	out := new(ArticleCategory)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *service) CategoryListByPage(ctx context.Context, in *CategoryListReq, opts ...client.CallOption) (*ArticleCategoryList, error) {
	req := c.c.NewRequest(c.name, "Service.CategoryListByPage", in)
	out := new(ArticleCategoryList)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Service service

type ServiceHandler interface {
	Create(context.Context, *Article, *Article) error
	Update(context.Context, *Article, *Article) error
	Delete(context.Context, *Article, *Article) error
	InfoByID(context.Context, *ID, *Article) error
	ListByPage(context.Context, *ListReq, *ArticleList) error
	CreateCategory(context.Context, *ArticleCategory, *ArticleCategory) error
	UpdateCategory(context.Context, *ArticleCategory, *ArticleCategory) error
	DeleteCategory(context.Context, *ArticleCategory, *ArticleCategory) error
	CategoryInfoByID(context.Context, *ID, *ArticleCategory) error
	CategoryListByPage(context.Context, *CategoryListReq, *ArticleCategoryList) error
}

func RegisterServiceHandler(s server.Server, hdlr ServiceHandler, opts ...server.HandlerOption) error {
	type service interface {
		Create(ctx context.Context, in *Article, out *Article) error
		Update(ctx context.Context, in *Article, out *Article) error
		Delete(ctx context.Context, in *Article, out *Article) error
		InfoByID(ctx context.Context, in *ID, out *Article) error
		ListByPage(ctx context.Context, in *ListReq, out *ArticleList) error
		CreateCategory(ctx context.Context, in *ArticleCategory, out *ArticleCategory) error
		UpdateCategory(ctx context.Context, in *ArticleCategory, out *ArticleCategory) error
		DeleteCategory(ctx context.Context, in *ArticleCategory, out *ArticleCategory) error
		CategoryInfoByID(ctx context.Context, in *ID, out *ArticleCategory) error
		CategoryListByPage(ctx context.Context, in *CategoryListReq, out *ArticleCategoryList) error
	}
	type Service struct {
		service
	}
	h := &serviceHandler{hdlr}
	return s.Handle(s.NewHandler(&Service{h}, opts...))
}

type serviceHandler struct {
	ServiceHandler
}

func (h *serviceHandler) Create(ctx context.Context, in *Article, out *Article) error {
	return h.ServiceHandler.Create(ctx, in, out)
}

func (h *serviceHandler) Update(ctx context.Context, in *Article, out *Article) error {
	return h.ServiceHandler.Update(ctx, in, out)
}

func (h *serviceHandler) Delete(ctx context.Context, in *Article, out *Article) error {
	return h.ServiceHandler.Delete(ctx, in, out)
}

func (h *serviceHandler) InfoByID(ctx context.Context, in *ID, out *Article) error {
	return h.ServiceHandler.InfoByID(ctx, in, out)
}

func (h *serviceHandler) ListByPage(ctx context.Context, in *ListReq, out *ArticleList) error {
	return h.ServiceHandler.ListByPage(ctx, in, out)
}

func (h *serviceHandler) CreateCategory(ctx context.Context, in *ArticleCategory, out *ArticleCategory) error {
	return h.ServiceHandler.CreateCategory(ctx, in, out)
}

func (h *serviceHandler) UpdateCategory(ctx context.Context, in *ArticleCategory, out *ArticleCategory) error {
	return h.ServiceHandler.UpdateCategory(ctx, in, out)
}

func (h *serviceHandler) DeleteCategory(ctx context.Context, in *ArticleCategory, out *ArticleCategory) error {
	return h.ServiceHandler.DeleteCategory(ctx, in, out)
}

func (h *serviceHandler) CategoryInfoByID(ctx context.Context, in *ID, out *ArticleCategory) error {
	return h.ServiceHandler.CategoryInfoByID(ctx, in, out)
}

func (h *serviceHandler) CategoryListByPage(ctx context.Context, in *CategoryListReq, out *ArticleCategoryList) error {
	return h.ServiceHandler.CategoryListByPage(ctx, in, out)
}
